### ISSUE TITLE
[Discussion] Sponsors logos / Logo Bar implementation

### ISSUE THREAD

**Issue by tina-la** [elastic/elasticon#18]
Figma prototype handed off here: https://github.com/elastic/website-requests/issues/1482#issuecomment-1712098788.

Discuss before implementation:
- Content model
- Reference or no reference, etc.

## [Prototype: Figma](https://www.figma.com/file/ZWQeIqeoGHKiPqRdU3aTod/ElasticON-Tour-2023%2F2024?type=design&node-id=1397-2031&mode=design&t=lneF8LHqTc8xK74P-0#544254862)
<img width="716" alt="Screenshot 2023-09-08 at 12 00 49 PM" src="https://github.com/elastic/elasticon/assets/55425389/cb6ea332-7442-4dd0-8313-523fa84a105d">

**Comment by tina-la** [comment]
@johnbarrierwilson - For project visibility, I created this ticket for discussion so decisions don't get lost in Slack.
Implementation ticket will be created after decisions have been made.

Everyone is calling it the sponsors module, but this is already an existing module called [Logo Bar content type](https://app.contentstack.com/#!/stack/bltefdd0b53724fa2ce/entries?page=1&page_size=30&query=%7B%22queryObject%22%3A%7B%22%24and%22%3A%5B%7B%22locale%22%3A%7B%22%24eq%22%3A%22en-us%22%7D%7D%5D%2C%22_content_type_uid%22%3A%7B%22%24in%22%3A%5B%22logo_bar%22%5D%7D%7D%7D&search=logo%20) in the [Elastic Contentstack](https://app.contentstack.com/#!/stack/bltefdd0b53724fa2ce/entries?page=1&page_size=30).

For this implementation, I plan to use the same content model and naming convention for Logo Bar into the [ElasticON Contentstack](https://app.contentstack.com/#!/stack/blta2ce60e5241e282f/dashboard).

Let me know if you're good with this. If there are any concerns, please let me know. Thanks!

**Comment by johnbarrierwilson** [comment]
Sounds good to me! The logo bar content type will just be a reference for each ElasticON event, right?

**Comment by tina-la** [comment]
@johnbarrierwilson - Yes, the logo bar will be a reference. Thanks!

---

**Decisions made thus far:**

- Sponsor module will be called `Logo Bar` to match [Elastic CMS stack](https://app.contentstack.com/#!/stack/bltefdd0b53724fa2ce/entries?page=1&page_size=30).
- `Logo Bar` will be its own content type and referenced to a page like Elastic CMS stack.
- Web development can begin as web development direction has been confirmed. Development tracking here: 
https://github.com/elastic/elasticon/issues/19
