### ISSUE TITLE
[Discussion] Marketo forms

### ISSUE THREAD

**Issue by tina-la** [elastic/elasticon#25]
Discussion for Marketo form implementation: https://staging-website.elastic.co/events/elasticon/bangalore/register

**Decisions:** TBD

**Comment by tina-la** [comment]
**[Slack thread:](https://elastic.slack.com/archives/G01KYSHH7D2/p1695324094979979?thread_ts=1695247196.857459&cid=G01KYSHH7D2)** Plan for Bangalore.

**Comment by johnbarrierwilson** [comment]
Closing this since we implemented the registration form on the main website here: https://www.elastic.co/bangalore-registration
